### ISSUE TITLE
dcoker service running even for containerd

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10373]
```

medya@~/workspace/minikube (master) $ minikube start --container-runtime=containerd
😄  minikube v1.17.1 on Darwin 11.2
✨  Automatically selected the docker driver. Other choices: hyperkit, parallels, virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=3890MB) ...
📦  Preparing Kubernetes v1.20.2 on containerd 1.4.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

medya@~/workspace/minikube (master) $ minikube ssh

docker@minikube:~$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-02-05 20:01:08 UTC; 32s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 685 (dockerd)
      Tasks: 13
     Memory: 59.7M
     CGroup: /docker/066532b5ecaee2efce00eaf4303c267213fae706a2b4545b3edc483fccfece4b/system.slice/docker.service
             └─685 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Feb 05 20:01:07 minikube dockerd[685]: time="2021-02-05T20:01:07.864164700Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" modul
e=grpc
Feb 05 20:01:07 minikube dockerd[685]: time="2021-02-05T20:01:07.864319700Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 05 20:01:07 minikube dockerd[685]: time="2021-02-05T20:01:07.884834000Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Feb 05 20:01:07 minikube dockerd[685]: time="2021-02-05T20:01:07.889034600Z" level=info msg="Loading containers: start."
Feb 05 20:01:08 minikube dockerd[685]: time="2021-02-05T20:01:08.001177500Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferr
ed IP address"
Feb 05 20:01:08 minikube dockerd[685]: time="2021-02-05T20:01:08.048786100Z" level=info msg="Loading containers: done."
Feb 05 20:01:08 minikube dockerd[685]: time="2021-02-05T20:01:08.074148700Z" level=info msg="Docker daemon" commit=8891c58 graphdriver(s)=overlay2 version=20.10.2
Feb 05 20:01:08 minikube dockerd[685]: time="2021-02-05T20:01:08.074231500Z" level=info msg="Daemon has completed initialization"
Feb 05 20:01:08 minikube systemd[1]: Started Docker Application Container Engine.
Feb 05 20:01:08 minikube dockerd[685]: time="2021-02-05T20:01:08.097624700Z" level=info msg="API listen on /run/docker.sock"
```

**Comment by medyagh** [comment]
this only affects kic base and not VM drivers
```
xcode-select: note: install requested for command line developer tools
● docker.service - Docker Application Container Engine
     Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-02-05 20:14:46 UTC; 29s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 2193 (dockerd)
      Tasks: 137
     Memory: 66.8M
     CGroup: /system.slice/docker.service
             ├─2193 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.p
             ├─2201 containerd --config /var/run/docker/containerd/containerd.toml --log-level info
             ├─3049 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 27d5a710ac6bcecd4199da014c45ec88e2d9ccdf82339aa62acfb1bb87fafd3a -address /var/run/docker/contain
             ├─3063 /usr/bin/containerd-shim-runc-v2 -namespace moby -id a20b844898e7e674746e7e63cdffbace31a129ac1b0b44318b78079343a6d76e -address /var/run/docker/contain
             ├─3068 /usr/bin/containerd-shim-runc-v2 -namespace moby -id c764bf5a398199e21fc63ce9556f0e4d8711c1e1d6a6ff0a96bde94a1dfc2a60 -address /var/run/docker/contain
             ├─3122 /usr/bin/containerd-shim-runc-v2 -namespace moby -id a2a0454f1c04a13fa3d1e53ed6471f4b2519b50563e920a3f616f4380802d040 -address /var/run/docker/contain
             ├─3268 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 3c4359ce48ebc5ef221c6c91c2fd4e00f013dd49b122dc4e4e15737bc1dbbc9f -address /var/run/docker/contain
             ├─3326 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 7a6a6b01167250fdfc6c74a6f5ee8487c1c042abc49c6b46f153e8806a65c49f -address /var/run/docker/contain
             ├─3341 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 81173d94fc0fa451edcec753ca24c95f68a484e563f6c3723e7e89c6d60385f1 -address /var/run/docker/contain
             └─3387 /usr/bin/containerd-shim-runc-v2 -namespace moby -id bd8d1776d4c7284811e840fea56c30e65e2e10afc7e4d4c5258d0649b4d11c4f -address /var/run/docker/contain

Feb 05 20:14:50 minikube systemd[1]: /usr/lib/systemd/system/docker.service:11: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 05 20:14:54 minikube dockerd[2201]: time="2021-02-05T20:14:54.043644395Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.conta
Feb 05 20:14:54 minikube dockerd[2201]: time="2021-02-05T20:14:54.046329770Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.conta
Feb 05 20:14:54 minikube dockerd[2201]: time="2021-02-05T20:14:54.054762194Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.conta
Feb 05 20:14:54 minikube dockerd[2201]: time="2021-02-05T20:14:54.093082142Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.conta
Feb 05 20:14:54 minikube dockerd[2201]: time="2021-02-05T20:14:54.690834818Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.conta
```

**Comment by afbjorklund** [comment]
Different packaging for KIC, so the service works differently too... This can be socket-activated, as you've seen

**Comment by afbjorklund** [comment]
Still wondered why it decided to start the service ? Something must have triggered the docker socket, perhaps ?

**Comment by medyagh** [comment]
@afbjorklund fixed in this PR seems to be okay without it starting https://github.com/kubernetes/minikube/pull/10374

**Comment by afbjorklund** [comment]
Disabling the socket is the big hammer, but it would be interesting to know what was trying to use docker.sock (for containerd)

**Comment by afbjorklund** [comment]
It is the kubelet starting it, and it still happens. Need to shut it down harder.
