### ISSUE TITLE
Connection to the server <minikubeVMHost>:<Port> was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by unmarshall** [kubernetes/minikube#1465]
**BUG REPORT**
**Minikube version** (use `minikube version`): v0.18.0

Similar to Issue #1381 
 
**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS Sierra 10.12.4 (16E195)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
"Boot2DockerURL": "file:///Users/i062009/.minikube/cache/iso/minikube-v0.18.0.iso"
- **Install tools**: Homebrew was used to install minikube
- **Others**: 
- **Docker Version**: 17.03.1-ce-mac5 (16048)
- **Kubectl version**: 
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
When i attempt to start minikube using `minikube start --vm-driver=xhyve` it throws the following exception:

Starting local Kubernetes cluster...
Starting VM...
E0507 23:23:02.690334   19712 start.go:116] Error starting host: Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded.
 Retrying.
E0507 23:23:02.693671   19712 start.go:122] Error starting host:  Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

This issue gets resolved when issue `minikube delete` and start it again. This time it starts properly. However when i invoke `kubectl get pods` then it throws the following exception:

The connection to the server 192.168.64.5:8443 was refused - did you specify the right host or port?

**What you expected to happen**:
I expect to see that kubectl should return me a list of pods but instead it throws an exception.

**How to reproduce it** (as minimally and precisely as possible):
On Mac OSX Sierra install xhyve (latest stable version), docker, minikube using the versions listed above, start minikube using xhyve vm driver and invoke `kubectl get pods`

**Anything else do we need to know**:
I have attached the logs that were collected using `minikube logs` for further analysis.
It has been recommended in #1381 that if we downgrade to 0.17.0 minikube version then it would solve the problem. I will try that out and see if that works.

**Comment by unmarshall** [comment]
[minikube.log.zip](https://github.com/kubernetes/minikube/files/981821/minikube.log.zip)

**Comment by unmarshall** [comment]
Move to 0.17.0 resolved the issues. This only means that 0.18.0 has too many issues and even the basic things are not working. Will wait for patches to be delivered for this release and only then consume it.

**Comment by aaron-prindle** [comment]
This issue is cause by #1422 which was fixed with #1434.  Updating to v0.19.0 should resolve this.

**Comment by sandugandhi** [comment]
I installed everything  (latest v0.19.0) from scratch today on my Ubuntu 16.04.2 machine. 
Still facing same issue. See #1038

**Comment by elcergey** [comment]
Facing same problem on versions from 17.0 to 19.1. Tried on Windows Server 2016, RHEL 7, Windows 10, Ubuntu on Windows (14.04).

**Comment by unmarshall** [comment]
Well i had to reinstall everything again due to corruption in minikube installation and now nothing works again. I have even tried using 0.19.1 and the issue still persists.
I guess minikube is not stable and it surely does not work reliably behind corporate proxy.
