### ISSUE TITLE
Version 19 broke ingress 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#1521]
**BUG REPORT** :

**Minikube version** (use `minikube version`):
minikube version: v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac Os Sierra 10.12.4 (16E195
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):     "DriverName": "virtualbox",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):  "Boot2DockerURL": "file:///Users/z001r9y/.minikube/cache/iso/minikube-v0.19.0.iso",
- **Install tools**:
- **Others**:

**What happened**:

K8Guard Project's minikube doesnt work in minikube version 19, there isn't any connectivity between cassandra service and my container. downgrading to minikube version 18.

**What you expected to happen**:

I expected connectivity between cassandra-service and k8guard-discover-service

**How to reproduce it** (as minimally and precisely as possible):
Deploy K8Guard in minikube using this README https://github.com/k8guard/k8guard-start-from-here/

it will work in minikube version 18 and not in miniukube version 19. currently, I will have to update K8guard docs that users have so people avoid using version 19. unforuntately.

**Anything else do we need to know**:
looking at the CHANGELOG for verison 19 I suspect these two items are the reason for my problem:
```
- Increased localkube boot speed by removing dependency on the network being up
- Updated nginx ingress to v0.9-beta.4
```

**Comment by dlorenc** [comment]
I'm not familiar with k8guard, but I want to try to repro this. Do you have a minimal set of yamls I can try this on?

It looks like you're asking user to pin to kubernetes 1.5.1, any reason for that instead of using 1.6?

**Comment by medyagh** [comment]
k8guard is an open source project by Target Corp, we havent annouced it yet. it is an auditing system for kuberentes. we wanna be able to audit 1.5.1 kuberentes clusters. you can easily install k8guard following the readme here ( a very few steps) https://github.com/k8guard/k8guard-start-from-here

and minikube has an option to start it with a different version. that we take advantage of.

**Comment by dlorenc** [comment]
> and minikube has an option to start it with a different version that we take advantage of. unfortuntely that option broke ingress in minikube 19.

Could you possibly help me understand how ingress got broken? I don't see any "kind: Ingress" types in that repo.

**Comment by medyagh** [comment]
By ingress Imeant ingress connections to the cassandra service, my deploymetns cant connect to cassandra.

For example, action micro-service deployment
https://github.com/k8guard/k8guard-start-from-here/blob/master/minikube/action/k8guard-action-deployment.yaml

in versioion 19 of minikube wont be able to talk to cassandra service which I defined here
https://github.com/k8guard/k8guard-start-from-here/blob/master/minikube/core/cassandra-svc.yaml

in all previous version of minikube (befor 19) which I tried, it works fine. only in version 19, my cassandra service is not reachable (network wise) by other deployment. thats what I meant by ingress. not the ingress kind of kubernetes.

**Comment by medyagh** [comment]
also related to this issue, https://github.com/kubernetes/minikube/issues/1505

**Comment by webwurst** [comment]
Is this also possible fixed by https://github.com/kubernetes/minikube/pull/1577 ?

**Comment by medyagh** [comment]
@webwurst 
no it is not fixed, I just tested with the latest version of minikube and the bug is back
