### ISSUE TITLE
virtualbox: unable to start minikube on macOS Ventura

### ISSUE THREAD

**Issue by andriymahats** [kubernetes/minikube#15274]
### What Happened?

After upgrading macOS to Ventura from Monterey the minikube start started to fail with the response:

```sh
😄  minikube v1.27.1 on Darwin 13.0
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=8192MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
🔥  Creating virtualbox VM (CPUs=2, Memory=8192MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

❌  Exiting due to IF_VBOX_NOT_VISIBLE: Failed to start host: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Suggestion: Reboot to complete VirtualBox installation, verify that VirtualBox is not blocked by your system, and/or use another hypervisor
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222
    ▪ https://github.com/kubernetes/minikube/issues/5817
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9922957/log.txt)

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by crengifo** [comment]
same issue, i've tried minikube delete and start and update virtualbox and nothing...

**Comment by hakjoonglee** [comment]
Same issue. I also tried minikube delete and start and updated VirtualBox version 7.0.2

**Comment by TestRep1** [comment]
i have exactly the same issue.. Has anyone found a solution to this problem?

**Comment by crengifo** [comment]
Update 7.12 virtual box, solved the problem for me

**Comment by spowelljr** [comment]
@crengifo So it's working for you now on macOS Ventura with VirtualBox 7.02?

**Comment by andriymahats** [comment]
> Update 7.02 virtual box, solved the problem for me directly from virtual box site

hmm, tried to reinstall latest virtual box (7.0.2 r154219). Issue remains for me

**Comment by crengifo** [comment]
> @crengifo So it's working for you now on macOS Ventura with VirtualBox 7.02?

Yes, reinstalling obviously.

**Comment by nrudnyk** [comment]
> Update 7.02 virtual box, solved the problem for me directly from virtual box site

didn't helped. Still facing same problem as described in the OP

**Comment by W07FP4X** [comment]
Same.  Host only adapters are no longer support on mac.  I'm running podman until we get a VB driver update.
`brew install podman`
`podman machine init --cpus 2 --memory 2048 --rootful`
`podman machine start`
`minikube config set driver podman`
 `minikube start`
 `minikube status`

**Comment by DmitriyStoyanov** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/1244213/202638832-a4dcce1e-d01d-42bd-ab90-b4e3f9a36301.png">
Possibly we face with such issue because of in VirtualBox Host-only Adapter is DEPRECATED

**Comment by martininnotec** [comment]
@DmitriyStoyanov yep this is definitely the reason - as @W07FP4X  said it's because Host-only adapters are no longer supported on Mac OS, we need to use a Host-only network instead.

I've configured my virtual machine manually to use this network setup and can connect to Minikube on the running VM.

![Screenshot 2022-11-18 at 08 07 29](https://user-images.githubusercontent.com/60384664/202653259-9892820d-fa62-440e-aecb-9fcb264fa315.png)


![Screenshot 2022-11-18 at 08 07 36](https://user-images.githubusercontent.com/60384664/202653308-bedbf7cc-a04e-4246-aa78-d3bc75f67bff.png)

![Screenshot 2022-11-18 at 08 08 33](https://user-images.githubusercontent.com/60384664/202653336-b92e7d9d-7d79-47b4-be1b-dddaeeed1de5.png)

The only problem is the Minikube start command still wants to create/see a host-only adapter so fails and it doesn't seem to be able to see the running VM.

Unfortunately, I think we will need to look at running alternatives like Docker or Podman until a Virtualbox driver update for Minikube is released.

**Comment by spowelljr** [comment]
Thanks for discovering the root cause of the issue, I believe the change will need to be in the upstream project https://github.com/machine-drivers/machine, but I could be wrong.

**Comment by martininnotec** [comment]
> Thanks for discovering the root cause of the issue, I believe the change will need to be in the upstream project https://github.com/machine-drivers/machine, but I could be wrong.

Yes, this code needs to be updated to use the Host-only network instead of the adapter for the new macOS.

https://github.com/machine-drivers/machine/blob/master/drivers/virtualbox/network.go 

Has someone raised this with the upstream project?

**Comment by jevy-wangfei** [comment]
down grade virtualbox to 6.* would be able to resolve this Host-ony Adapter deprecated issue.

**Comment by martininnotec** [comment]
> down grade virtualbox to 6.* would be able to resolve this Host-ony Adapter deprecated issue.

I tried the downgrade to Virtualbox 6.1 and the issue still persists when starting minikube.

**Comment by d1ck50n** [comment]
Encounter similar isssue, and i downgrade virtualbox to older version 6.1 @ https://www.virtualbox.org/wiki/Download_Old_Builds_6_1
I'm able to launch minikube using command : minikube start --driver=virtualbox

**Comment by pavgup** [comment]
Just one more macOS user having no success with minikube because of this problem.

**Comment by afbjorklund** [comment]
> Has someone raised this with the upstream project?

The upstream project (docker-machine) is dead, so the feature will have to be developed by minikube...

It is possible to use the machine-driver organisation for _hosting_ the patches, but it's **not** the upstream.

https://github.com/docker/machine/tree/master/drivers/virtualbox

* https://github.com/kubernetes/minikube/issues/9952

----

For newer macOS, it needs to use `hostonlynet` instead of `hostonlyif`.

Then the interface will be created by the OS, when the network is used.

This also means that libmachine can't set the IP anymore, it will have to check which one it received.

But the docs say only that it (Host-Only Adapter ) is deprecated, not that it is removed already ?

**Comment by afbjorklund** [comment]
This is the tracker issue that @spowelljr created: (github.com/docker/machine is archived and read-only)

* https://github.com/machine-drivers/machine/issues/38

**Comment by afbjorklund** [comment]
> Unfortunately, I think we will need to look at running alternatives like Docker or Podman until a Virtualbox driver update for Minikube is released.

If you run Docker or Podman with Oracle VirtualBox instead of their "Desktop", you would have the same problem...

You can try another hypervisor driver for Minikube, such as the QEMU driver. Or run minikube in Docker or Podman ?

But the best would be to fix the machine driver.

**Comment by spowelljr** [comment]
An upstream fix was merged (https://github.com/machine-drivers/machine/pull/39), I created a PR to update the dependency (https://github.com/kubernetes/minikube/pull/15729). Once the binaries are built I'll link them for anyone experiencing the issue to confirm if it resolves the issue for them, thanks.

**Comment by spowelljr** [comment]
If anyone could test these out and confirm whether it fixes the issue.

Intel CPU: https://storage.googleapis.com/minikube-builds/15729/minikube-darwin-amd64
Apple CPU: https://storage.googleapis.com/minikube-builds/15729/minikube-darwin-arm64

**Comment by martininnotec** [comment]
> machine-drivers/machine#39

Hi @spowelljr - I've installed from the binary and still get the same error, only difference is I now get a warning at the top saying minikube doesn't support Virtualbox - am I doing something wrong?

![Screenshot 2023-01-30 at 19 17 47](https://user-images.githubusercontent.com/60384664/215574274-a0430f13-b2bc-44d6-a6d7-7dc5225d467c.png)

**Comment by martininnotec** [comment]
> d.HostLoopbackReachable = true

Thanks, @afbjorklund - I'm not sure where this is configured, however looking at the config.json file on the minikube machine it appears to already have that value set...

![Screenshot 2023-01-30 at 19 53 34](https://user-images.githubusercontent.com/60384664/215581494-9ab4940b-4f37-49ff-8031-7de076c386d6.png)

**Comment by afbjorklund** [comment]
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/registry/drvs/virtualbox/virtualbox.go#L58

I don't think it uses those values in the JSON, i.e. it only uses the "ClusterConfig" and not the "Driver" from libmachine

**Comment by afbjorklund** [comment]
Hmm, maybe it would read the defaults. The best would be to look in the log, and see how VBox was started

**Comment by afbjorklund** [comment]
Doh! That fix was for a totally _different_ issue.

* https://github.com/kubernetes/minikube/issues/15566

The network change is still left to do, sorry about the noise.

**Comment by martininnotec** [comment]
> 

No worries @afbjorklund - any ETA on a fix for the Host-only Adapter issue?

**Comment by fffffreedom** [comment]
> > 
> 
> No worries @afbjorklund - any ETA on a fix for the Host-only Adapter issue?

same question, anyone helps?

**Comment by afbjorklund** [comment]
There is no ETA, I am not sure if anyone is working on the problem at the moment ?

**Comment by subhankar-banerjee** [comment]
any idea when this will be resolved ? It was working last year and suddenly I can see few days back it stopped working ..

is that problem started after Mac update ?

**Comment by Antsthebul** [comment]
> > down grade virtualbox to 6.* would be able to resolve this Host-ony Adapter deprecated issue.
> 
> I tried the downgrade to Virtualbox 6.1 and the issue still persists when starting minikube.

This is the only thing that worked. Only had to reboot when prompted but
I needed to downgrade to this version to use VirtualBox, (and proceed with the "Allow" options in System pref > Security & Privacy). Running Mac OS v12.6.7
