### ISSUE TITLE
Cilium CNI plugin fails with missing kernel module(s)

### ISSUE THREAD

**Issue by varjoinen** [kubernetes/minikube#17780]
### What Happened?

Started minikube with:

```
minikube start --cni=cilium
```

The Kubernetes cluster starts, but Cilium will stay in `CrashLoopBackOff`and logging:

```
...
level=warning msg="BPF system config check: NOT OK." error="CONFIG_NET_SCH_INGRESS kernel parameter or module is required (needed for: Essential eBPF infrastructure)" subsys=linux-datapath
...
level=warning msg="+ tc qdisc replace dev cilium_vxlan clsact" subsys=datapath-loader
level=warning msg="RTNETLINK answers: Operation not supported" subsys=datapath-loader
...
level=warning msg="We have an error talking to the kernel" subsys=datapath-loader
...
level=fatal msg="Error while creating daemon" error="error while initializing daemon: failed while reinitializing datapath: exit status 1" subsys=daemon
```

There has been [similar issue](https://github.com/cilium/cilium/issues/20858) reported earlier at Cilium side and missing kernel modules have been pointed out.

One can see that related kernel modules are missing from the minikube container:

```
> docker exec -it minikube /bin/sh    
# zcat /proc/config.gz | grep CONFIG_NET_SCH_INGRESS
# zcat /proc/config.gz | grep CONFIG_NET_CLS_ACT    
# 
```

The same issue can be seen if minikube is started without CNI plugin and Cilium Helm chart is used to install it.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13657773/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by maksymilian-mulawa-form3** [comment]
My guess is, you are using `4.26.0-1` version of `Docker Desktop` on `macOS`, try to downgrade it to [4.25.2](https://docs.docker.com/desktop/release-notes/#4252) using following steps. 

1. Download your desired version from the [Release Notes](https://docs.docker.com/desktop/release-notes/#4252).
2. Open the download, drag "Docker" to "Applications"
3. Chose to "Replace" the existing installation
4. Run Docker desktop

It seems that in `4.26.*` some major configuration changes were applied to `docker-for-macos` VM kernel, e.g. [hugetlbfs filesystem not available](https://github.com/docker/for-mac/issues/7115)

**Comment by afbjorklund** [comment]
The new Docker VM also broke both vfat and 9p filesystem support, so this all sounds like more of the same...

**Comment by dgageot** [comment]
Sorry all for this issue. This will be fixed in 4.27.0. In the meantime, yes, you can use 4.25.2. Sorry again.

**Comment by El-Coder** [comment]
Also ran into same issue 4.25.2 fixed it for me

**Comment by maksymilian-mulawa-form3** [comment]
This issue was resolved in [Docker Desktop 4.27.0](https://docs.docker.com/desktop/release-notes/#4270).

**Comment by ofcRS** [comment]
> This issue was resolved in [Docker Desktop 4.27.0](https://docs.docker.com/desktop/release-notes/#4270).
I'm still experiencing the issue at 4.27 macOS. However, when I downgrade to version 4.25.x, the problem is resolved.

**Comment by dgageot** [comment]
@ofcRS do you have exactly the same error message or is it a bit different?
