### ISSUE TITLE
`service` command executes wrong helper

### ISSUE THREAD

**Issue by bigon** [kubernetes/minikube#19878]
### What Happened?

As you can see bellow, minikube tries to execute `kvm2`, but this seems wrong.

The driver is called `docker-machine-driver-kvm2` (and not in the PATH)

Running debian unstable

```
$ minikube service --all
|-----------|------------|-------------|--------------|
| NAMESPACE |    NAME    | TARGET PORT |     URL      |
|-----------|------------|-------------|--------------|
| default   | kubernetes |             | No node port |
|-----------|------------|-------------|--------------|
😿  service default/kubernetes has no node port
❗  Services [default/kubernetes] have type "ClusterIP" not meant to be exposed, however for local development minikube allows you to access this !
E1029 14:47:25.572916   77507 out.go:502] unable to execute error getting ssh port: get port 22 for "minikube": kvm2 container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exec: "kvm2": executable file not found in $PATH
stdout:

stderr:
: template: error getting ssh port: get port 22 for "minikube": kvm2 container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exec: "kvm2": executable file not found in $PATH
stdout:

stderr:
:1:90: executing "error getting ssh port: get port 22 for \"minikube\": kvm2 container inspect -f \"'{{(index (index .NetworkSettings.Ports \"22/tcp\") 0).HostPort}}'\" minikube: exec: \"kvm2\": executable file not found in $PATH\nstdout:\n\nstderr:\n" at <index .NetworkSettings.Ports "22/tcp">: error calling index: index of untyped nil - returning raw string.

❌  Exiting due to DRV_PORT_FORWARD: error getting ssh port: get port 22 for "minikube": kvm2 container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exec: "kvm2": executable file not found in $PATH
stdout:

stderr:


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_service_7307d14e4bcde4344d1f5773b0e0f52f3b39b30f_0.log                 │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```

### Attach the log file

[minikube_service_7307d14e4bcde4344d1f5773b0e0f52f3b39b30f_0.log](https://github.com/user-attachments/files/17557785/minikube_service_7307d14e4bcde4344d1f5773b0e0f52f3b39b30f_0.log)

### Operating System

Other

### Driver

KVM2

**Comment by bigon** [comment]
[logs.txt](https://github.com/user-attachments/files/17558018/logs.txt)

**Comment by bigon** [comment]
BTW I find an other similar bugs #18825

**Comment by medyagh** [comment]
@prezha do you mind taking a look?

**Comment by medyagh** [comment]
@bigon do you have multiple profiles ? do you mind sharing
"minikube profile list"

**Comment by bigon** [comment]
Hello,

No only one profile

```
$ minikube profile list
|----------|-----------|---------|----------------|------|---------|---------|-------|----------------|--------------------|
| Profile  | VM Driver | Runtime |       IP       | Port | Version | Status  | Nodes | Active Profile | Active Kubecontext |
|----------|-----------|---------|----------------|------|---------|---------|-------|----------------|--------------------|
| minikube | kvm2      | docker  | 192.168.39.211 | 8443 | v1.31.0 | Running |     1 | *              | *                  |
|----------|-----------|---------|----------------|------|---------|---------|-------|----------------|--------------------|
```

**Comment by prezha** [comment]
looks like the problem is that we're always calling the kic-based logic (specifically, the startKicServiceTunnel() func) without checking first if a kic driver is used for given profile, and in this and the other #18825 case, users are using vm/kvm driver, so it fails

the code segment that's making a call without checking (introduced in pr #17877 on 3rd of april this year):
https://github.com/kubernetes/minikube/pull/17877/files#diff-72b0db9f1698ff6131feb23cdcc885688b228eddf388bf36db516dd6e0ede9a8R172-R174

**Comment by Ritikaa96** [comment]
Hi @bigon given the above statement this issue should be resolved. can you confirm?

**Comment by bigon** [comment]
Hello,

Well according to my understanding, the problem is not fixed

**Comment by bigon** [comment]
Hello,

The problem still exists in 1.35.0

**Comment by bigon** [comment]
Still present in 1.36.0

**Comment by prezha** [comment]
@bigon, thanks for opening this issue and for your patience

if you want to try out the fix, please download the binaries from [here](https://github.com/kubernetes/minikube/actions/runs/15368682391/artifacts/3234922477) and let us know if it works for you

**Comment by bigon** [comment]
@prezha Looks good indeed, thank you

**Comment by prezha** [comment]
great, thanks @bigon !
