### ISSUE TITLE
Pulling two kicbase images

### ISSUE THREAD

**Issue by VeselovAndrey** [kubernetes/minikube#21534]
### What Happened?

Hello,

Using minikube 1.37 with Docker under Windows (WSL).

When starting an instance using containers, minikube pulls
gcr.io/k8s-minikube/kicbase:v0.0.48
But it also pulls gcr.io/k8s-minikube/kicbase (without a tag) and uses that image.

<img width="1245" height="128" alt="Image" src="https://github.com/user-attachments/assets/afdc94cc-739f-4935-990d-014a106ca2e8" />

### Attach the log file

😄  minikube v1.37.0 on Microsoft Windows 11 Pro 10.0.26100.6584 Build 26100.6584
✨  Automatically selected the docker driver
📌  Using Docker Desktop driver with root privileges
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🚜  Pulling base image v0.0.48 ...
🔥  Creating docker container (CPUs=2, Memory=32100MB) ...
❗  Failing to connect to https://registry.k8s.io/ from inside the minikube container
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.34.0 on Docker 28.4.0 ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

### Operating System

Windows

### Driver

Docker

**Comment by medyagh** [comment]
@VeselovAndrey do you mind pasting the laststart logs ?
~/minikube/logs/lastStart.txt
and also `docker ps` after the minikube start?


and I think the reason might be minikube saving the docker image that it could not download first time locally
```
❗ Failing to connect to https://registry.k8s.io/ from inside the minikube container
```

my guess is minikube downloaded the image from Github Tar when it failed to download from GCR and minikube is Warning that you dont have access to GCR ! so thats why you dont have a tag. it is probablly a network issue that minikube failed over to downloading the tar ball

**Comment by bobsira** [comment]
Seems like I'm not getting the same issues on my end, sharing a screen shot below

**Comment by bobsira** [comment]
<img width="928" height="283" alt="Image" src="https://github.com/user-attachments/assets/269af326-2586-46dd-9cf7-cc21862ef25b" />

**Comment by VeselovAndrey** [comment]
@medyagh Thank you for response.

> do you mind pasting the laststart logs ?

Sorry, can't paste entire logs because of some security restrictions, but your guess was almost correct. I can't connect to registry.k8s.io not because of network issue but ...

```text
I0911 10:30:30.814354   25580 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0911 10:30:30.859573   25580 ssh_runner.go:195] Run: curl.exe -sS -m 2 https://registry.k8s.io/
I0911 10:30:30.862691   25580 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0911 10:30:30.865293   25580 ssh_runner.go:195] Run: cat /version.json
I0911 10:30:30.867902   25580 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0911 10:30:30.904925   25580 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:56682 SSHKeyPath:[redacted]\.minikube\machines\minikube\id_rsa Username:docker}
I0911 10:30:30.914298   25580 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:56682 SSHKeyPath:[redacted]\.minikube\machines\minikube\id_rsa Username:docker}
W0911 10:30:30.993899   25580 start.go:868] [curl.exe -sS -m 2 https://registry.k8s.io/] failed: curl.exe -sS -m 2 https://registry.k8s.io/: Process exited with status 127
stdout:

stderr:
bash: line 1: curl.exe: command not found
I0911 10:30:30.998082   25580 ssh_runner.go:195] Run: systemctl --version
```

After start 
```
> docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED          STATUS          PORTS                                                                                                                                  NAMES
385885a312da   gcr.io/k8s-minikube/kicbase:v0.0.48   "/usr/local/bin/entr…"   33 seconds ago   Up 32 seconds   127.0.0.1:56420->22/tcp, 127.0.0.1:56418->2376/tcp, 127.0.0.1:56417->5000/tcp, 127.0.0.1:56419->8443/tcp, 127.0.0.1:56416->32443/tcp   minikube
```

**Comment by medyagh** [comment]
glad the mystrie was solved :)

**Comment by VeselovAndrey** [comment]
@medyagh  Not solved. Why container missing _curl_?

> bash: line 1: curl.exe: command not found

It's inside container, not Windows.

**Comment by VeselovAndrey** [comment]
@medyagh Can you please take a look at this issue?

**Comment by MeetTak** [comment]
@VeselovAndrey @medyagh 
this is a normal behavior
when u run minikube with docker driver, it typically creates or downloads two primary images on ur host machine to manage the cluster env

1.kicbase image
this is the foundation of ur minikube cluster
Why it exists: Minikube uses this image to create a container that acts as a virtual node. Inside this container, a full Kubernetes environment (including its own isolated Docker daemon) is started.

2.and a digest image

docker system df -v
imp lines from this config
gcr.io/k8s-minikube/kicbase:v0.0.50
IMAGE ID: ffefe6978189
SHARED SIZE: 1.37GB
UNIQUE SIZE: 506.9MB
CONTAINERS: 0

<none>:<none>
IMAGE ID: eb4fec00e8ad
SHARED SIZE: 1.37GB
UNIQUE SIZE: 506.9MB
CONTAINERS: 1

what’s this tells us
the <none> image is not unused
docker reports:
CONTAINERS: 1

for eb4fec00e8ad

that means there is (or was) a container referencing that image
So Minikube is likely:
1. Pulling a digest-pinned image (eb4fec00e8ad)
2. Creating the node container from it
3. Tagging another image as v0.0.50
4. Leaving both image records around

use the following command to check which image is being used
docker inspect minikube —format ‘{{.Image}}’

it will return:
sha256:eb4fec00e8ad...

note: image id might differ on ur machine, but tags will be similar

<img width="1609" height="128" alt="Image" src="https://github.com/user-attachments/assets/08316f5a-ce32-4153-8648-7ad736cbcf1f" />
