### ISSUE TITLE
hyperv: blocked on kube-proxy (solved by recreating virtual switch)

### ISSUE THREAD

**Issue by BGaudreault-EDR** [kubernetes/minikube#3765]
On Windows 10 Ent 1709 (16299.371) with Docker Desktop v2.0.0.3 (31259) Build 8858db3 in a PowerShell Admin command window I type the command 'minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary vSwitch" (though I had to run the command twice to get this far!) and Minikube starts in Hyper-V, which I can see in the console and I can login, but PowerShell displays the following:

o   minikube v0.34.1 on windows (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing hyperv VM for "minikube" ...
:   Waiting for SSH access ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running hyperv VM for "minikube" ...
:   Waiting for SSH access ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running hyperv VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 10.24.8.149
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.13.3 ...
:   Relaunching Kubernetes v1.13.3 using kubeadm ...
:   Waiting for kube-proxy to come back up ...
!   **Error restarting cluster**: restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

I then run 'minikube status' and get the following:

host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 10.24.8.149

I then run 'kubectl get pods -n kube-system' and get the following:

NAME                                               READY   STATUS                      RESTARTS  AGE
etcd-minikube                                  1/1        Running                      0               27m
kube-addon-manager-minikube      1/1       Running                      2               26d
kube-apiserver-minikube                  1/1       Running                      0               27m
kube-controller-manager-minikube 1/1       Running                      0               27m
kube-scheduler-minikube                 1/1       Running                      1               1h
storage-provisioner                           0/1       CrashLoopBackOff  139              26d

Also I pre-configured Hyper-V with the following configurations I read were recommended for Windows:

• Hyper-V Manager > select local computer > Virtual Switch Manager... (right panel) > Create Virtual Switch (New virtual network switch, External) > Name: "Primary vSwitch"

• To address a bug in minikube for Windows (https://github.com/kubernetes/minikube/issues/2326) I turned off Dynamic Memory for minikube VM: Rrun 'minikube stop' first > Hyper-V Manager: right-click minikube VM > Settings... > Memory > UNcheck Enable Dynamic Memory > APPLY > optionally close Hyper-V manager.

**Comment by tstromberg** [comment]
I believe this should be addressed by minikube v0.35.0 - we no longer block on the kube-proxy in the same way. That said, you may run into some other issues. 

I encourage you to run `minikube delete` first to remove the previous half-setup state. Thanks!

**Comment by fracmak** [comment]
I found minikube delete didn't solve my problem. I had to delete the network interface for virtualbox and let minikube recreate it before everything went back to normal

**Comment by tstromberg** [comment]
OK. Thanks for the update! What did minikube v0.35.0 say before deleting the network interface?

**Comment by fracmak** [comment]
same error message above in this issue. I could ssh in and see that kube-proxy was indeed running, but whatever reason it wouldn't get past that step until I deleted the network interface

**Comment by tstromberg** [comment]
Thanks!

**Comment by Ben197** [comment]
Minikube in Windows Prof is still not working, I can't disable the dynamic ram like adviced because the kube is running. I going to try it on my LInux system.  Windows never works with open source tooling.
![PowerShellMiniKube](https://user-images.githubusercontent.com/19990181/55653417-bdd1ff80-57ee-11e9-9895-6ebd26c749bf.PNG)

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!

**Comment by Ben197** [comment]
I have minikube successfully running on my Linux Ubuntu system.
Thx for your support anyway!!
Maybe I try it later again via the hyper-V driver with minikube v1.1.0.
