### ISSUE TITLE
Improve "The host-only adapter we just created is not visible" hint

### ISSUE THREAD

**Issue by vanrein** [kubernetes/minikube#4222]
**The exact command to reproduce the issue**:

brew cask install minikube
minikube start

**The full output of the command that failed**:

😄  minikube v1.0.1 on darwin (amd64)
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

💣  Unable to start VM: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**:

Mac OS X 10.14.4 (this is probably the pivotal point)

I hadn't upgraded VirtualBox to a version that runs on the OS. but hadn't tried to run it since the last OS upgrade.  I was already on a 5.2.x version.  So, **you might want to mention not just an upgrade to 5.0.12 but (also) an upgrade to a version that matches the OS** -- and does not popup "you cannot run this version of VirtualBox on this OS".  That differs from the (first-time-user) hint that you are now giving.  The popup appears when running VirtualBox manually, but not when run from Kubernetes.

After this fix, it proceeded beyond this point (up to the next problem to fix, I/O Error on certificates).

**Comment by tstromberg** [comment]
Fixed in v1.1.

**Comment by cmaliwal** [comment]
@tstromberg , It's not fixed on 1.1.1. 
I am getting the same issue:

```
Chirags-MacBook-Pro:~ chirag$ minikube version
minikube version: v1.1.1
Chirags-MacBook-Pro:~ chirag$ minikube delete
🙄  "minikube" cluster does not exist
🙄  "minikube" profile does not exist
Chirags-MacBook-Pro:~ chirag$ minikube start
😄  minikube v1.1.1 on darwin (amd64)
💿  Downloading Minikube ISO ...
 131.29 MB / 131.29 MB [============================================] 100.00% 0s
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0615 07:51:17.459525   12314 start.go:529] StartHost: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

💣  Unable to start VM
❌  Error:         [VBOX_HOST_ADAPTER] create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Advice:        Reboot to complete VirtualBox installation, and verify that VirtualBox is not blocked by your system
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by guhanselvaraj** [comment]
I got struck with the same issue for more than 2 days. Looking for some help. 
M-C02WN0UHHV2Q:scripts d95x$ minikube start
😄  minikube v1.1.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0616 13:51:40.748866    2681 start.go:529] StartHost: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

💣  Unable to start VM
❌  Error:         [VBOX_HOST_ADAPTER] create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Advice:        Reboot to complete VirtualBox installation, and verify that VirtualBox is not blocked by your system
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by DorrinPk** [comment]
This got fixed after I upgraded to VirtualBox 6.0.10.

**Comment by bios-transspecies** [comment]
found same issue with 6.0.12

**Comment by polaroi8d** [comment]
Same issue in 6.1

**Comment by jpramos123** [comment]
Same issue with virtualbox 6.1.24

**Comment by hokimr** [comment]
minikube start --driver=docker 
solved it with

**Comment by Gresdy** [comment]
您好, 您的邮件永宏已经收到！

**Comment by Gresdy** [comment]
您好, 您的邮件永宏已经收到！
