### ISSUE TITLE
Deleted hostpath PVs stuck in released state after minikube restart

### ISSUE THREAD

**Issue by debugmiller** [kubernetes/minikube#4546]
Dynamically provisioned PVs are stuck in the released state if minikube is restarted before deleting the pvc. It seems that the Provisioner Identity changes on reboot which causes the hostpath provisioner to ignore the PV. 

**The exact command to reproduce the issue**:
```
cat << EOF | kubectl apply -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 10Mi
  accessModes:
    - ReadWriteOnce
EOF

minikube stop
minikube start
kubectl delete pvc mypvc
kubectl get pv
```

**The full output of the command that failed**:
```
$ minikube ssh tail /tmp/storage-provisioner.INFO
...
I0620 17:17:11.727823       1 controller.go:1040] deletion of volume "pvc-8674aa0d-937a-11e9-b2aa-000c29bcb67d" ignored: ignored because identity annotation on PV does not match ours
```

**The output of the `minikube logs` command**:
N/A

**The operating system version**:
MacOS 10.14.5
minikube v1.1.1
kubernetes 1.14.3

**Comment by fenglixa** [comment]
Yes, I reproduced this issue. Thanks for you logged the issue. I will provide PR for fixing it.

BR
-Francis

**Comment by fenglixa** [comment]
Reason of this issue: After minikube restart, the pv name was changed, that's why report deletion failed.

**Comment by fenglixa** [comment]
This issue could be reproduced easily with the steps as logged. But I am afraid this can't be fixed by minikube code.  After VM restart, the sandbox ID was changed also.

**Comment by tstromberg** [comment]
AFAIK, this is still an issue with minikube v1.4 as we have not yet swapped out the storage provisioner addon used.

**Comment by medyagh** [comment]
I believe this is Dupe of https://github.com/kubernetes/minikube/issues/4546 

if you don't mind I will close this issue in favor ohttps://github.com/kubernetes/minikube/issues/4546 to cenetralize the work on the issue.

**Comment by joma74** [comment]
Still an issue under 1.6.1. Note that @medyagh dupe reference is a self reference to this very issue. 
Any advice/workaround how to kick PV out appreciated.

**Comment by fredgate** [comment]
Yes still have this probem.
There is no duplicated issue : #4546 is this issue itself.
@medyagh I think that you can reopen this issue

**Comment by fredgate** [comment]
ping @tstromberg

**Comment by medyagh** [comment]
Anyone likes to contribute logs to this issue?

minikube logs

**Comment by oraclesamdrake** [comment]
Still an issue on OSX in Minikube 1.26.0 with the virtualbox driver.

![image](https://user-images.githubusercontent.com/58493292/178062994-a55fe12c-c706-443f-8e5f-60cb01361d8b.png)

**Comment by oraclesamdrake** [comment]
[minikube.logs.txt](https://github.com/kubernetes/minikube/files/9074802/minikube.logs.txt)

**Comment by maxb** [comment]
/reopen

Just because no one has worked on it doesn't mean this confirmed bug has stopped being a problem.
