### ISSUE TITLE
kubelet command-line arguments redundant with newly enabled config file

### ISSUE THREAD

**Issue by thomas-riccardi** [kubernetes/minikube#5719]
With #5697 (fixing #5329) the `kubelet` command-line arguments are/would be redundant (or may be different than) the newly used `/var/lib/kubelet/config.yaml`.

It's probably better to have the values only once: either cmdline or config file.

I'm not even sure if all the values are the same: 
- the cmdline is built in `/pkg/minikube/bootstrapper/kubeadm/versions.go`
- the kubelet config file is defined in `/pkg/minikube/bootstrapper/kubeadm/templates.go`, generated in `/pkg/minikube/bootstrapper/kubeadm/kubeadm.go` as a `kubeadmCfg`, but it's not really kubeadmin config (it's kubelet config), isn't it? (and there is a `kubeletCfg` next to it, but it contains other things... I'm lost :) )

**Comment by medyagh** [comment]
closing this issue. 
I believe this issue has be resolved by the PR. please feel free to reopen

**Comment by thomas-riccardi** [comment]
@medyagh it's not really resolved, it was deemed acceptable for now, with guidance to clean this later (here: https://github.com/kubernetes/minikube/pull/5697#issuecomment-547186812).

I think this issue here could be used to track the mentioned cleanup.
