### ISSUE TITLE
Upgrade to Go 1.7

### ISSUE THREAD

**Issue by mistydemeo** [kubernetes/minikube#615]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): 0.10.0

**Environment**:
- **OS** 10.12
- **VM Driver** n/a
- **Docker version** 1.12.1
- **Install tools**: Installed via binary from releases page

**What happened**:

The first time I ran `minikube version`, I received the following error and stack trace:

```
failed MSpanList_Insert 0x38c9000 0x30c91d61b884 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x17fd240, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90 fp=0x7fff5fbff390 sp=0x7fff5fbff378
runtime.(*mSpanList).insert(0x3543ca8, 0x38c9000)
	/usr/local/go/src/runtime/mheap.go:933 +0x293 fp=0x7fff5fbff3c0 sp=0x7fff5fbff390
runtime.(*mheap).freeSpanLocked(0x35434a0, 0x38c9000, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be fp=0x7fff5fbff428 sp=0x7fff5fbff3c0
runtime.(*mheap).grow(0x35434a0, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:675 +0x2a0 fp=0x7fff5fbff480 sp=0x7fff5fbff428
runtime.(*mheap).allocSpanLocked(0x35434a0, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:553 +0x4e3 fp=0x7fff5fbff4d8 sp=0x7fff5fbff480
runtime.(*mheap).alloc_m(0x35434a0, 0x1, 0x15, 0x0)
	/usr/local/go/src/runtime/mheap.go:437 +0x119 fp=0x7fff5fbff508 sp=0x7fff5fbff4d8
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41 fp=0x7fff5fbff538 sp=0x7fff5fbff508
runtime.systemstack(0x7fff5fbff558)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7fff5fbff540 sp=0x7fff5fbff538
runtime.(*mheap).alloc(0x35434a0, 0x1, 0x10000000015, 0xeb8f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63 fp=0x7fff5fbff588 sp=0x7fff5fbff540
runtime.(*mcentral).grow(0x35450a0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93 fp=0x7fff5fbff5f0 sp=0x7fff5fbff588
runtime.(*mcentral).cacheSpan(0x35450a0, 0x35398d8)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d fp=0x7fff5fbff630 sp=0x7fff5fbff5f0
runtime.(*mcache).refill(0x38c5000, 0x15, 0x7fff5fbff698)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc fp=0x7fff5fbff668 sp=0x7fff5fbff630
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b fp=0x7fff5fbff688 sp=0x7fff5fbff668
runtime.systemstack(0x7fff5fbff728)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab fp=0x7fff5fbff690 sp=0x7fff5fbff688
runtime.mallocgc(0x180, 0x16975a0, 0x0, 0x800000000)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0x7fff5fbff768 sp=0x7fff5fbff690
runtime.newobject(0x16975a0, 0x353a430)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0x7fff5fbff790 sp=0x7fff5fbff768
runtime.malg(0x8000, 0x353a7e0)
	/usr/local/go/src/runtime/proc.go:2634 +0x27 fp=0x7fff5fbff7c8 sp=0x7fff5fbff790
runtime.mpreinit(0x353b120)
	/usr/local/go/src/runtime/os1_darwin.go:140 +0x1f fp=0x7fff5fbff7e0 sp=0x7fff5fbff7c8
runtime.mcommoninit(0x353b120)
	/usr/local/go/src/runtime/proc.go:494 +0x105 fp=0x7fff5fbff828 sp=0x7fff5fbff7e0
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:434 +0x79 fp=0x7fff5fbff870 sp=0x7fff5fbff828
runtime.rt0_go(0x7fff5fbff8a8, 0x2, 0x7fff5fbff8a8, 0x0, 0x0, 0x2, 0x7fff5fbffa40, 0x7fff5fbffa49, 0x0, 0x7fff5fbffa51, ...)
	/usr/local/go/src/runtime/asm_amd64.s:138 +0x132 fp=0x7fff5fbff878 sp=0x7fff5fbff870
```

I installed minikube using the Darwin binary from the releases tab.

**How to reproduce it** (as minimally and precisely as possible):

I have been unable to reproduce this. :(

**Comment by r2d4** [comment]
Thanks for opening up this.  I found this issue about macOS Sierra and compiled golang binaries that might be related to this, https://github.com/golang/go/issues/16570

We currently compile all of our darwin binaries with go 1.6. It looks like they've fixed this in go 1.7.  I haven't gotten a chance to try it on macOS Sierra yet, but I suspect this might be a bigger problem as people start upgrading.  

Was this just a one time panic or are you still not able to get it working?

**Comment by r2d4** [comment]
We are going to repurpose this bug to track upgrading to go 1.7 as kubernetes is on it.

**Comment by mistydemeo** [comment]
I can't repro; it only happened once.

**Comment by dlorenc** [comment]
Fixed with #623

**Comment by inigo-montoyahh** [comment]
@dlorenc is there any way to get a patch or minor version release put together - i'm running into this along with many other go related issues as I'm trying to use this?

**Comment by r2d4** [comment]
@inigo-montoyahh you can grab a binary from our CI on a merged PR 
https://github.com/kubernetes/minikube#ci-builds

We can also start doing nightly builds if theres enough interest.

**Comment by PierrickI3** [comment]
I also have this when I create a deployment, followed by a get rs & get po

OS: Mac Sierra
Minikube version: 0.10.0

deployment.yaml:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microservice-ping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        microservice: ping
    spec:
      containers:
      - name: ping
        image: pierrickl/docker-ping
        ports:
        - containerPort: 3000
```

bash script to create my deployment (create.sh):
```
#!/bin/bash

kubectl create -f deployment.yaml --record

echo
echo '== DEPLOYMENTS =='
kubectl get deployments
echo
echo '== REPLICA SETS =='
kubectl get rs
echo
echo '== PODS =='
kubectl get po
echo
```

I get this:
```
pl190016ml:ping pierrick.lozach$ ./create.sh
deployment "microservice-ping" created

== DEPLOYMENTS ==
NAME                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
microservice-ping   1         1         1            0           0s

== REPLICA SETS ==
NAME                           DESIRED   CURRENT   AGE
microservice-ping-1358938894   1         1         0s

== PODS ==
failed MSpanList_Insert 0x1c99810 0x10e69de4a8a1 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x1a567a8, 0x1c99810)
	/usr/src/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x1a56600, 0x1, 0x1000000000a, 0xcf29)
	/usr/src/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x1a5da78, 0x1c998e0)
	/usr/src/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0x1c7e000, 0xc20000000a, 0x1c998e0)
	/usr/src/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc2082054e0 sp=0xc2082054d8
runtime.mallocgc(0x90, 0xd80380, 0xc200000001, 0xc2082b1ef0)
	/usr/src/go/src/runtime/malloc.go:178 +0x849 fp=0xc208205590 sp=0xc2082054e0
runtime.newarray(0xd80380, 0x11, 0xc2082b1ef0)
	/usr/src/go/src/runtime/malloc.go:365 +0xc1 fp=0xc2082055c8 sp=0xc208205590
runtime.makeslice(0x11c5320, 0x11, 0x11, 0x0, 0x0, 0x0)
	/usr/src/go/src/runtime/slice.go:32 +0x15c fp=0xc208205610 sp=0xc2082055c8
math/big.nat.divLarge(0xc208076000, 0x10, 0x25, 0xc2082ab8c0, 0x20, 0x24, 0xc208076dc0, 0x20, 0x25, 0xc208085600, ...)
	/usr/src/go/src/math/big/nat.go:541 +0x2d0 fp=0xc2082057a8 sp=0xc208205610
math/big.nat.div(0xc208076000, 0x10, 0x25, 0xc2082ab8c0, 0x20, 0x24, 0xc208076dc0, 0x20, 0x25, 0xc208085600, ...)
	/usr/src/go/src/math/big/nat.go:519 +0x35a fp=0xc208205850 sp=0xc2082057a8
math/big.nat.expNNWindowed(0xc208076dc0, 0x20, 0x25, 0xc2081c1400, 0x10, 0x14, 0xc2081c12c0, 0x10, 0x14, 0xc208085600, ...)
	/usr/src/go/src/math/big/nat.go:1372 +0x82a fp=0xc208205ae0 sp=0xc208205850
math/big.nat.expNN(0xc208076000, 0x10, 0x25, 0xc2081c1400, 0x10, 0x14, 0xc2081c12c0, 0x10, 0x14, 0xc208085600, ...)
	/usr/src/go/src/math/big/nat.go:1260 +0x4b0 fp=0xc208205c78 sp=0xc208205ae0
math/big.nat.probablyPrime(0xc208085600, 0x10, 0x15, 0x14, 0x0)
	/usr/src/go/src/math/big/nat.go:1445 +0x887 fp=0xc208205df0 sp=0xc208205c78
math/big.(*Int).ProbablyPrime(0xc208211e00, 0x14, 0xc207febce5)
	/usr/src/go/src/math/big/int.go:741 +0x4a fp=0xc208205e20 sp=0xc208205df0
crypto/rsa.(*PrivateKey).Validate(0xc2081d3740, 0x0, 0x0)
	/usr/src/go/src/crypto/rsa/rsa.go:110 +0x108 fp=0xc208205f20 sp=0xc208205e20
crypto/x509.ParsePKCS1PrivateKey(0xc20822e000, 0x4a7, 0x4a7, 0xc2081d3740, 0x0, 0x0)
	/usr/src/go/src/crypto/x509/pkcs1.go:77 +0x702 fp=0xc2082060a8 sp=0xc208205f20
crypto/tls.parsePrivateKey(0xc20822e000, 0x4a7, 0x4a7, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/tls.go:259 +0x7d fp=0xc208206198 sp=0xc2082060a8
crypto/tls.X509KeyPair(0xc2081e14c4, 0x0, 0x200, 0xc20817d88b, 0x0, 0x200, 0xc208211da0, 0x1, 0x1, 0x0, ...)
	/usr/src/go/src/crypto/tls/tls.go:213 +0x394 fp=0xc208206390 sp=0xc208206198
k8s.io/kubernetes/pkg/client/transport.TLSConfigFor(0xc20806e0e0, 0xc208088990, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/transport.go:76 +0x2c0 fp=0xc2082064f0 sp=0xc208206390
k8s.io/kubernetes/pkg/client/transport.(*tlsTransportCache).get(0x1a3de60, 0xc20806e0e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/cache.go:53 +0x1f9 fp=0xc208206588 sp=0xc2082064f0
k8s.io/kubernetes/pkg/client/transport.New(0xc20806e0e0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/transport/transport.go:43 +0x149 fp=0xc2082065e8 sp=0xc208206588
k8s.io/kubernetes/pkg/client/restclient.TransportFor(0xc208214000, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/transport.go:36 +0x5a fp=0xc208206618 sp=0xc2082065e8
k8s.io/kubernetes/pkg/client/restclient.RESTClientFor(0xc208214000, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/config.go:145 +0x19b fp=0xc2082066c8 sp=0xc208206618
k8s.io/kubernetes/pkg/client/unversioned.New(0xc208077e00, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:49 +0xe2 fp=0xc2082067b8 sp=0xc2082066c8
k8s.io/kubernetes/pkg/client/unversioned.NegotiateVersion(0x0, 0xc208077e00, 0xc208211460, 0xc20805ea00, 0x7, 0x8, 0xc2081e43c0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:125 +0x75 fp=0xc208206a30 sp=0xc2082067b8
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientConfigForVersion(0xc208035fc0, 0xc20820c840, 0xc20820c840, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:76 +0x2f1 fp=0xc208206c48 sp=0xc208206a30
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientForVersion(0xc208035fc0, 0xc20820c840, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:103 +0xbc fp=0xc208206cb8 sp=0xc208206c48
k8s.io/kubernetes/pkg/kubectl/cmd/util.func·004(0xc208037420, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:237 +0x150 fp=0xc208206dd8 sp=0xc208206cb8
k8s.io/kubernetes/pkg/kubectl/resource.ClientMapperFunc.ClientForMapping(0xc208151b50, 0xc208037420, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/interfaces.go:45 +0x51 fp=0xc208206e08 sp=0xc208206dd8
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).visitorResult(0xc208197110, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:528 +0x8e9 fp=0xc208207538 sp=0xc208206e08
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).Do(0xc208197110, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:686 +0x33 fp=0xc208207630 sp=0xc208207538
k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc208154b40, 0x1c8fff0, 0xc208046008, 0xc20806ba00, 0xc20812f740, 0x1, 0x1, 0xc2080b5860, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:235 +0xead fp=0xc208207c38 sp=0xc208207630
k8s.io/kubernetes/pkg/kubectl/cmd.func·034(0xc20806ba00, 0xc20812f740, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:89 +0x6f fp=0xc208207ca0 sp=0xc208207c38
github.com/spf13/cobra.(*Command).execute(0xc20806ba00, 0xc20812f6c0, 0x1, 0x1, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f fp=0xc208207db8 sp=0xc208207ca0
github.com/spf13/cobra.(*Command).ExecuteC(0xc20806b600, 0xc20806ba00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db fp=0xc208207ec8 sp=0xc208207db8
github.com/spf13/cobra.(*Command).Execute(0xc20806b600, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a fp=0xc208207ef0 sp=0xc208207ec8
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101 fp=0xc208207f70 sp=0xc208207ef0
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f fp=0xc208207f98 sp=0xc208207f70
runtime.main()
	/usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc208207fe0 sp=0xc208207f98
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208207fe8 sp=0xc208207fe0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1a3f640)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by r2d4** [comment]
@PierrickI3 please ugrade to v0.11.0.  This isssue should be fixed in that version.

**Comment by PierrickI3** [comment]
@r2d4 My bad, my version is actually 0.11.0:

```
pl190016ml:cassandra pierrick.lozach$ minikube version
minikube version: v0.11.0
```

**Comment by copumpkin** [comment]
I've been noticing issues like this on Sierra on other go binaries built with Go 1.7.1, so it's possible that it isn't really fixed upstream yet. Still trying to figure out what's wrong with it to file/reopen a bug.
