### ISSUE TITLE
Docker: Failed to setup kubeconfig: inspect IP bridge network

### ISSUE THREAD

**Issue by srehanpk** [kubernetes/minikube#8131]
srahmed@hp:~$ minikube start
😄  minikube v1.10.1 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
E0513 19:32:35.665322   20138 start.go:95] Unable to get host IP: inspect IP bridge network "de7f841a3590\n13c6d9205f9b".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" de7f841a3590
13c6d9205f9b: exit status 1
stdout:

stderr:
Error: No such object: de7f841a3590
13c6d9205f9b

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "de7f841a3590\n13c6d9205f9b".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" de7f841a3590
13c6d9205f9b: exit status 1
stdout:

stderr:
Error: No such object: de7f841a3590
13c6d9205f9b

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by sharifelgamal** [comment]
What docker version are you using?

**Comment by sharifelgamal** [comment]
@afbjorklund Would this be related to having an old docker version?

**Comment by srehanpk** [comment]
> What docker version are you using?

Docker version 19.03.8,

**Comment by srehanpk** [comment]
> @afbjorklund Would this be related to having an old docker version?

Docker version 19.03.8,

**Comment by medyagh** [comment]
@srehanpk does deleting and recreating help ?
minikube delete
minikube start --driver=docker

**Comment by afbjorklund** [comment]
@sharifelgamal : I don't think so, it seems to be more about the weird linebreak in the ID ?

**Comment by afbjorklund** [comment]
I think it is due to the filter finding **two** network bridges, possibly due to #8034

` docker network ls --filter name=bridge --format "{{.ID}}"`

**Comment by srehanpk** [comment]
> @srehanpk
> the error tells that the minikube container doesnt exist anymore.
> are you running a system with low amount of ram?
> do you mind also pasting the output of :
> 
> ```
> docker ps -a | grep minikube
> ```
> 
> and also :
> 
> ```
> docker network ls
> ```
> 
> does deleting and recreating help ?
> minikube delete
> minikube start --driver=docker
> 
> it worth noting I just tried it on ubuntu 20.04 and same docker version and I have no issues. and our integration tests are ubuntu and debian too and they never had this problem but I really apperciate it that you made this issue, so we can find the root cause why this happens and we prevent it for others
srahmed@hp:~$ docker ps -a | grep minikube
srahmed@hp:~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
de7f841a3590        bridge              bridge              local
13c6d9205f9b        docker_gwbridge     bridge              local
ee09a402584e        host                host                local
k8rroic09yd5        ingress             overlay             swarm
7c859310e263        none                null                local

**Comment by irizzant** [comment]
I'm on Ubuntu 18.04 Docker 19.03.8
```sh
$ docker network ls --filter name=bridge --format "{{.ID}}"
580ef811af7b
58a53cab81bd
```
Starting minikube doesn't work:
```
minikube start --driver=docker
😄  minikube v1.10.0 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.1 on Docker 19.03.2 ...
E0513 22:14:50.386152    3767 start.go:95] Unable to get host IP: inspect IP bridge network "580ef811af7b\n58a53cab81bd".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" 580ef811af7b
58a53cab81bd: exit status 1
stdout:


stderr:
Error: No such object: 580ef811af7b
58a53cab81bd

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "580ef811af7b\n58a53cab81bd".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" 580ef811af7b
58a53cab81bd: exit status 1
stdout:


stderr:
Error: No such object: 580ef811af7b
58a53cab81bd


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```
But the docker container is running:
```
$ docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                                                                      NAMES
cf03dabc522b        gcr.io/k8s-minikube/kicbase:v0.0.10   "/usr/local/bin/entr…"   54 seconds ago      Up 50 seconds       127.0.0.1:32775->22/tcp, 127.0.0.1:32774->2376/tcp, 127.0.0.1:32773->5000/tcp, 127.0.0.1:32772->8443/tcp   minikube
```

**Comment by srehanpk** [comment]
> minikube delete
> minikube start --driver=docker

These commands dose not work

**Comment by srehanpk** [comment]
> @srehanpk
> the error tells that the minikube container doesnt exist anymore.
> are you running a system with low amount of ram?
> do you mind also pasting the output of :
> 
> ```
> docker ps -a | grep minikube
> ```
> 
> and also :
> 
> ```
> docker network ls
> ```
> 
> does deleting and recreating help ?
> minikube delete
> minikube start --driver=docker
> 
> it worth noting I just tried it on ubuntu 20.04 and same docker version and I have no issues. and our integration tests are ubuntu and debian too and they never had this problem but I really apperciate it that you made this issue, so we can find the root cause why this happens and we prevent it for others

srahmed@hp:~$ docker ps -a | grep minikube
8199c44ea6a7        gcr.io/k8s-minikube/kicbase:v0.0.10   "/usr/local/bin/entr…"   About a minute ago   Up 56 seconds       127.0.0.1:32807->22/tcp, 127.0.0.1:32806->2376/tcp, 127.0.0.1:32805->5000/tcp, 127.0.0.1:32804->8443/tcp   minikube

**Comment by afbjorklund** [comment]
> when node is part of a Swarm

I think this was the untested bit, I don't think we have any tests with both Swarm and Kubernetes...

Anyway, most likely the code was meant only to hit the default "bridge" and not the  docker_gwbridge
It was just an error, due to the word bridge appearing in both networks. The mentioned PR will fix.

**Comment by afbjorklund** [comment]
Here is some more information about docker_gwbridge:

https://docs.docker.com/network/overlay/

> When you initialize a swarm or join a Docker host to an existing swarm, two new networks are created on that Docker host:
> 
>     an overlay network called `ingress`, which handles control and data traffic related to swarm services. When you create a swarm service and do not connect it to a user-defined overlay network, it connects to the ingress network by default.
>     a bridge network called `docker_gwbridge`, which connects the individual Docker daemon to the other daemons participating in the swarm.


I do think that Swarm must have been enabled manually ?

**Comment by irizzant** [comment]
It's simply enabled with:
`docker swarm init`
on a host, in my case it's a single node Swarm.
Having a Swarm in a host makes multiple `bridge` network being used anyway.

**Comment by medyagh** [comment]
this seems to be a bug and we could do a better job in finding the correct bridge

**Comment by medyagh** [comment]
@afbjorklund I wonder if we still need to warn the user to disable swarm ? even if we detect the bridge correctly

**Comment by afbjorklund** [comment]
@medyagh : no idea, I haven't tried to mix Kubernetes and Docker Swarm myself

**Comment by irizzant** [comment]
Temporary workaround:
```
docker swarm leave --force
```
to make the node leave the Swarm and then minikube starts correctly.

**Comment by srehanpk** [comment]
> Temporary workaround:
> 
> ```
> docker swarm leave --force
> docker network prune
> ```
> 
> to make the node leave the Swarm and clean the unused networks, then minikube starts correctly.

Thanks a lot  now minikube is perfectly running 
thanks to all you guys for the support ;) ;) ;)

**Comment by srehanpk** [comment]
docker swarm leave --force
docker network prune

Finally this is the solution for my problem many thanks again to all of you .

**Comment by irizzant** [comment]
@srehanpk you should not close this issue, minikube should detect the bridge network correctly without forcing the host to leave the Swarm

**Comment by medyagh** [comment]
> his issue, minikube should detect the bridge network correctly without forcing the host to leave the Swarm

I agree this is on the milestone for minikube v1.12.0

**Comment by irizzant** [comment]
Very good thank you

**Comment by afbjorklund** [comment]
I think we should just go with something simple for now, like hardcoding "bridge".

**Comment by afbjorklund** [comment]
Since PR #8034 was closed, I'm hoping on @medyagh or @priyawadhwa

**Comment by medyagh** [comment]
dupe of other one.. in v1.13.0

**Comment by tebb** [comment]
In case this helps anyone ...

The Lando development environment's network name is 'lando_bridge_network', so you also get this issue - minikube fails to start.

Temporary fix allowing both minikube and Lando to start, is to:

# Stop any running Lando containers
lando poweroff

# Delete the Lando network
docker network rm lando_bridge_network

# Start minikube
minikube start

# Recreate the Lando network etc
lando rebuild -y

*** Obviously?? ... You may get conflicts if attempting to use the same ports from multiple containers

**Comment by afbjorklund** [comment]
> dupe of other one.. in v1.13.0

They can't _both_ be dupes ? But ~#8516~ duplicated this one.

**Comment by afbjorklund** [comment]
> In case this helps anyone ...
> 
> The Lando development environment's network name is 'lando_bridge_network', so you also get this issue - minikube fails to start.

Thanks for reporting, same root cause.

**Comment by kadern0** [comment]
Hi @afbjorklund, @medyagh I've run into this issue again. I thought it was already solved by  #8034  but it was closed. So just to be sure, is nobody working on fixing this issue? If not, I can give it a go.

**Comment by medyagh** [comment]
@srehanpk  on latest minikube I tried enabling swarm on mac and I have no issues, do we still have this issue ?

**Comment by kadern0** [comment]
With latest code, if you try this, it will fail:
```
docker network create testing_bridge
```

```
docker network list
NETWORK ID          NAME                DRIVER              SCOPE
ddb969f50f43        bridge              bridge              local
089b251a4b6a        host                host                local
442c7ccfda68        none                null                local
24546dec8368        testing_bridge      bridge              local
```
```
./out/minikube start --memory 2048 --cpus 2 -p testing2
😄  [testing2] minikube v1.12.3 on Ubuntu 20.04
✨  Automatically selected the docker driver. Other choices: kvm2, virtualbox
👍  Starting control plane node testing2 in cluster testing2
🔥  Creating docker container (CPUs=2, Memory=2048MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0820 08:17:07.515986  314891 start.go:97] Unable to get host IP: inspect IP bridge network "ddb969f50f43\n24546dec8368".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" ddb969f50f43
24546dec8368: exit status 1
stdout:


stderr:
Error: No such network: ddb969f50f43
24546dec8368

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "ddb969f50f43\n24546dec8368".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" ddb969f50f43
24546dec8368: exit status 1
stdout:


stderr:
Error: No such network: ddb969f50f43
24546dec8368


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

I don't think many users will run into this, but the way minikube is filtering the networks is prone to failure, it will pick all networks containing "bridge" and  mix them in a string with new line characters and then it will fail.

**Comment by medyagh** [comment]
here I tried on ubuntu as well
```
jenkins@instance-1:~$ docker swarm init
Swarm initialized: current node (vik7ym1zk79kxr44egvlldfnv) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-4212xfktioctsir1f1a1zan9fpqyc2zgeim23xbgk6w53xs3r3-0d2eo7veqxfvg30q9465p2h76 10.128.15.196:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

jenkins@instance-1:~$ docker info | grep Swa
 Swarm: active
WARNING: No swap limit support
jenkins@instance-1:~$ ./minikube-linux-amd64 start 
😄  minikube v1.12.3 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
💗  Kubectl not found in your path
👉  You can use kubectl inside minikube. For more information, visit https://minikube.sigs.k8s.io/docs/handbook/kubectl/
💡  For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/
```

**Comment by kadern0** [comment]
I was looking into this from this issue's perspective #8274 (that I closed in favor of this one because the underlying cause is the same).

**Comment by medyagh** [comment]
can you replicate this issue ? @kadern0

**Comment by kadern0** [comment]
Yes, just put you the steps to replicate the issue two comments above using the latest code. (Just create a docker network containing "bridge" before starting minikube)

**Comment by medyagh** [comment]
@kadern0 do you mind sharing me steps ? here I did and I couldn't reproduce

```

medya@~ $ docker network create bridge-1
241bbcbecb087d0a05188c9b910f735ceeff301d3310b816440c77d2cd6d4763
medya@~ $ minikube version
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5-dirty
medya@~ $ minikube delete --all
🔥  Deleting "minikube" in docker ...
🔥  Removing /Users/medya/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
🔥  Successfully deleted all profiles
medya@~ $ minikube start
😄  minikube v1.12.3 on Darwin 10.15.6
✨  Automatically selected the docker driver. Other choices: hyperkit, virtualbox
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2948MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube
```

**Comment by medyagh** [comment]
```
medya@~ $ docker network create testing_bridge
bdb3812f8ab7d7d5bbcb78dbb9e5336e9456fbaf82d4af118494188b5886e8ac


medya@~ $ minikube start
😄  minikube v1.12.3 on Darwin 10.15.6
✨  Automatically selected the docker driver. Other choices: hyperkit, virtualbox
❗  Your system has 16384MB memory but Docker has only 2996MB. For a better performance increase to at least 3GB.
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2948MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"


medya@~ $ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
2e2f5269fbdf        bridge              bridge              local
241bbcbecb08        bridge-1            bridge              local
6ceabcdd0b73        docker_gwbridge     bridge              local
7493d3908b3b        host                host                local
cnqffuv1zryx        ingress             overlay             swarm
32dd48b9b3da        minikube            bridge              local
de4265f5379d        none                null                local
bdb3812f8ab7        testing_bridge      bridge              local

```

**Comment by kadern0** [comment]
```
$ minikube version
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5-dirty
```
Cleaning up and fresh start
```
pcaderno@pcaderno-desktop$ minikube delete --all
🔥  Deleting "minikube" in docker ...
🔥  Removing /home/pcaderno/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
🔥  Successfully deleted all profiles
pcaderno@pcaderno-desktop$ minikube start 
😄  minikube v1.12.3 on Ubuntu 19.10
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=7800MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```
All good, now let's break it
```
pcaderno@pcaderno-desktop$ minikube stop
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🛑  1 nodes stopped.
```
```
pcaderno@pcaderno-desktop$ docker network create testing_bridge
8622100c89c5e6ed0f4fb957a9117a3bfe85f53aac5de40ec7e74b4c9af9b8ac
```
```
pcaderno@pcaderno-desktop$ minikube start
😄  minikube v1.12.3 on Ubuntu 19.10
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0821 09:11:33.527143    4903 start.go:97] Unable to get host IP: inspect IP bridge network "f631e95f4100\n8622100c89c5".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" f631e95f4100
8622100c89c5: exit status 1
stdout:


stderr:
Error: No such network: f631e95f4100
8622100c89c5

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "f631e95f4100\n8622100c89c5".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" f631e95f4100
8622100c89c5: exit status 1
stdout:


stderr:
Error: No such network: f631e95f4100
8622100c89c5


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```
List docker networks
```
pcaderno@pcaderno-desktop$ docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
f631e95f4100        bridge               bridge              local
meiftgx9pkqf        devdocs-server-net   overlay             swarm
db34ce28a755        host                 host                local
9mxl3y16ro30        ingress              overlay             swarm
e945b60808c9        none                 null                local
8622100c89c5        testing_bridge       bridge              local
```
Delete testing network and start minikube
```
pcaderno@pcaderno-desktop$ docker network rm testing_bridge
testing_bridge
pcaderno@pcaderno-desktop$ minikube start
😄  minikube v1.12.3 on Ubuntu 19.10
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```
It works fine again. Do you have a linux box available for testing?

**Comment by davidshen84** [comment]
Hi,

I think I am hit by this issue as well. I am on Gentoo distro. I think the `docker_gwbridge` on my system is created by docker, so I don't think I can just delete it. Is there's a walkaround/fix to this issue?

```
NETWORK ID          NAME                DRIVER              SCOPE
83eca32b5df3        bridge              bridge              local
0f6b47c0882d        docker_gwbridge     bridge              local
21d9995cf792        host                host                local
tgv0ut9u3sgw        ingress             overlay             swarm
8ab892bf9aac        none                null                local
```

```
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.14.7
 Git commit:        48a66213fe
 Built:             Sat Aug  8 06:09:21 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.7
  Git commit:       48a66213fe
  Built:            Sat Aug  8 06:08:46 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

```
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

**Comment by kadern0** [comment]
@davidshen84 the PR that will close this issue is this one -> https://github.com/kubernetes/minikube/pull/9094 if you need a quick temporary fix, you can always use my code from here -> https://github.com/kubernetes/minikube/pull/9062

**Comment by davidshen84** [comment]
Thanks Pablo!

**Comment by tstromberg** [comment]
Fixed by #9062

**Comment by tstromberg** [comment]
I'm going to leave this open until the v1.13 release as so many people are running into it. As a workaround until the release later this week, you should be able to use minikube from head (or delete the bridge network):

https://storage.googleapis.com/minikube-builds/9160/minikube-darwin-amd64
https://storage.googleapis.com/minikube-builds/9160/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/9160/minikube-windows-amd64.exe

If this updated build does not help, please let us know immediately so that we can fix it before the release.

**Comment by RoSk0** [comment]
Upgrading to v1.13.0 fixed the issue for me (was using 1.12.3).

Thanks!

**Comment by tstromberg** [comment]
@RoSk0 - thank you for the confirmation!

**Comment by mythreyi1905** [comment]
> Upgrading to v1.13.0 fixed the issue for me (was using 1.12.3).
> 
> Thanks!

This works !!! I had docker swarm initialized and even when I disabled it followed by deleting of .docker/config.json file, I kept encountering the same error. Upgrading minikube works. Thanks @RoSk0
