### ISSUE TITLE
virtualbox: The host-only adapter we just created is not visible -> GUEST_NOT_FOUND on retry

### ISSUE THREAD

**Issue by neel8989** [kubernetes/minikube#9192]
PS C:\Users\Neel> minikube start --driver=virtualbox
* minikube v1.13.0 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
* Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Neel\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Neel\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'

_Originally posted by @neel8989 in https://github.com/kubernetes/minikube/issues/9130#issuecomment-687811881_

**Comment by neel8989** [comment]
> PS C:\Users\Neel> minikube start --driver=virtualbox
> 
> * minikube v1.13.0 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
> * Using the virtualbox driver based on user configuration
> * Starting control plane node minikube in cluster minikube
> * Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
> * Deleting "minikube" in virtualbox ...
>   ! StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
> * Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Neel.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Neel.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> * Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
> 
> _Originally posted by @neel8989 in [#9130 (comment)](https://github.com/kubernetes/minikube/issues/9130#issuecomment-687811881)_

**Comment by tstromberg** [comment]
@neel8989 - do you mind sharing the output of `minikube start --driver=virtualbox --alsologtostderr -v=2`?

Also, can you report which version of VirtualBox you are using?

**Comment by neel8989** [comment]
@tstromberg issue has been resolved now.
Previously Am using virtualbox-6.1.14,then uninstall latest version and installed virtualbox-5.2.44 now it is working.

**Comment by vagdevik** [comment]
I had the same issue. So I did the following and it was solved!!!

1. `minikube delete`
2.  download minikube and install it again
3. download Virtualbox and instal it again
4. `minikube start --driver=virtualbox`

**Comment by alidurgun** [comment]
/reopen
I have exactly same issue and minikube delete and reinstall does not solve this problem. I have virtualbox 6.1.32 and latest minikube version. I am trying to execute minikube start --driver=virtualbox --no-vtx-check command but this fail message appears all the time.
X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\alidu\.minikube\machines\minikube\config.json: The system cannot find the file specified.

**Comment by AnusreeV1** [comment]
> /reopen I have exactly same issue and minikube delete and reinstall does not solve this problem. I have virtualbox 6.1.32 and latest minikube version. I am trying to execute minikube start --driver=virtualbox --no-vtx-check command but this fail message appears all the time. X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\alidu.minikube\machines\minikube\config.json: The system cannot find the file specified.

Hi, did you find a fix for it?
