### ISSUE TITLE
RSRC_INSUFFICIENT_CORES on WSL2 Windows

### ISSUE THREAD

**Issue by davidchieregato** [kubernetes/minikube#9373]
minikube start --driver=docker
😄  minikube v1.13.1 on Ubuntu 20.04
✨  Using the docker driver based on user configuration

⛔  Exiting due to RSRC_INSUFFICIENT_CORES: Docker has less than 2 CPUs available, but Kubernetes requires at least 2 to be available

The issues related to this error are talking about using minikube with a mono core machine, but in my case the error doesn't make sense at all as my device is a 16 core setup.

With `sudo minikube start --driver=none` instead I get the same error as in #8568

**Comment by priyawadhwa** [comment]
Hey @davidchieregato could you try increasing the number of cores available to Docker and see if that resolves the issue?

**Comment by davidchieregato** [comment]
Solved with
`minikube config set cpus 16`

**Comment by chiehpower** [comment]
Dear experts, 

Even I already set up 16, but it still appeared the same error message...
```
$ minikube start --driver=docker                                                                                                                         
😄  minikube v1.14.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=16, Memory=8000MB) ...

⛔  Exiting due to RSRC_INSUFFICIENT_CORES: Docker has less than 2 CPUs available, but Kubernetes requires at least 2 to be available
```
Is there any idea?
Thank you.

**Comment by afbjorklund** [comment]
@chiehpower : doesn't seem to be about Windows at all ? On Ubuntu, the docker engine should use all of the hosts CPUs.

Please open a **new** ticket.

**Comment by chiehpower** [comment]
> @chiehpower : doesn't seem to be about Windows at all ?
> How many cores / CPU does the docker host have ?
> 
> Please open a **new** ticket.

It was working on Linux indeed, but I saw the error message was similar so I thought the solution might be woked.
I will create a new issue. Thanks for your reply!!!

**Comment by sachincalsoft-dev** [comment]
Helped @davidchieregato 's solution, set cpus<=available cpus
Thanks
